import Head from 'next/head'
import Link from 'next/link'

import { Todolist } from '~/components/mol/List/todoList'
import styles from '~/styles/Home.module.css'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>Todo List</div>

        <div className={styles.todoList}>
          <Link href="/create" passHref legacyBehavior>
            <div className={styles.createCard}>Create Todo</div>
          </Link>
          <Todolist />
        </div>
      </main>
    </>
  )
}

export default Home
